name = "peerjs-worker-do"
main = "src/index.ts"
compatibility_date = "2023-11-21"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
[[durable_objects.bindings]]
name = "PEER_SERVER"
class_name = "PeerServerDO"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/learning/using-durable-objects#configure-durable-object-classes-with-migrations
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["PeerServerDO"]
